// AUTO-GENERATED by scripts/generate-agent-catalog.mjs. DO NOT EDIT.
#pragma once

#include <cstddef>
#include <string_view>

namespace mydaw::agent {

inline constexpr int kAgentCatalogFormatVersion = 1;
extern const char kAgentCatalogSha256[];
const char* agentCatalogJson();
std::size_t agentCatalogJsonSize();
bool isAgentBatchableOperation(std::string_view name);

// Prepared agent scripts (MCP prompts). Embedded copy of shared/agent/prompts.json.
extern const char kAgentPromptsSha256[];
const char* agentPromptsJson();
std::size_t agentPromptsJsonSize();

} // namespace mydaw::agent
