/**
 * extract-bravura.mjs — regenerates ui/src/components/SheetMusic/bravura.ts.
 *
 * The Sheet Music pane engraves with real SMuFL outlines rather than approximations, but
 * we do not want to ship (or load at runtime) a ~500 KB font for ~40 glyphs. This script
 * pulls the Bravura SVG font plus its metadata and vendors only the glyphs we draw,
 * keeping the outlines in font units so nothing is lost to path rewriting.
 *
 * Bravura © Steinberg Media Technologies GmbH, SIL Open Font License 1.1 —
 * see docs/licenses/Bravura-OFL-1.1.txt.
 *
 *   node scripts/extract-bravura.mjs
 *
 * Requires network access; the sources are:
 *   https://raw.githubusercontent.com/rism-digital/verovio/develop/fonts/Bravura/Bravura.svg
 *   https://raw.githubusercontent.com/rism-digital/verovio/develop/fonts/Bravura/bravura_metadata.json
 */

import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "ui", "src", "components", "SheetMusic", "bravura.ts");
const BASE = "https://raw.githubusercontent.com/rism-digital/verovio/develop/fonts/Bravura";

/** SMuFL codepoints for every glyph the pane draws. */
const WANT = {
  brace: 0xe000,
  gClef: 0xe050,
  cClef: 0xe05c,
  fClef: 0xe062,
  timeSig0: 0xe080,
  timeSig1: 0xe081,
  timeSig2: 0xe082,
  timeSig3: 0xe083,
  timeSig4: 0xe084,
  timeSig5: 0xe085,
  timeSig6: 0xe086,
  timeSig7: 0xe087,
  timeSig8: 0xe088,
  timeSig9: 0xe089,
  noteheadDoubleWhole: 0xe0a0,
  noteheadWhole: 0xe0a2,
  noteheadHalf: 0xe0a3,
  noteheadBlack: 0xe0a4,
  augmentationDot: 0xe1e7,
  flag8thUp: 0xe240,
  flag8thDown: 0xe241,
  flag16thUp: 0xe242,
  flag16thDown: 0xe243,
  flag32ndUp: 0xe244,
  flag32ndDown: 0xe245,
  flag64thUp: 0xe246,
  flag64thDown: 0xe247,
  accidentalFlat: 0xe260,
  accidentalNatural: 0xe261,
  accidentalSharp: 0xe262,
  accidentalDoubleSharp: 0xe263,
  accidentalDoubleFlat: 0xe264,
  restWhole: 0xe4e3,
  restHalf: 0xe4e4,
  restQuarter: 0xe4e5,
  rest8th: 0xe4e6,
  rest16th: 0xe4e7,
  rest32nd: 0xe4e8,
  rest64th: 0xe4e9,
};

const fetchText = async (url) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
};

const svg = await fetchText(`${BASE}/Bravura.svg`);
const meta = JSON.parse(await fetchText(`${BASE}/bravura_metadata.json`));

const attr = (s, name) => {
  const m = new RegExp(`${name}="([^"]*)"`).exec(s);
  return m ? m[1] : null;
};

const byCode = new Map();
const glyphRe = /<glyph\b([^>]*?)\/>/g;
let m;
while ((m = glyphRe.exec(svg)) !== null) {
  const uni = attr(m[1], "unicode");
  const cm = uni && /&#x([0-9a-fA-F]+);/.exec(uni);
  if (!cm) continue;
  byCode.set(parseInt(cm[1], 16), attr(m[1], "d"));
}
console.log(`parsed ${byCode.size} glyphs`);

const paths = [];
const boxes = [];
for (const [name, code] of Object.entries(WANT)) {
  const d = byCode.get(code);
  if (!d) {
    console.warn(`MISSING ${name} U+${code.toString(16).toUpperCase()}`);
    continue;
  }
  paths.push(`  ${name}: ${JSON.stringify(d)},`);
  const bb = meta.glyphBBoxes?.[name];
  if (!bb) {
    console.warn(`no bbox for ${name}`);
    continue;
  }
  const [l, b] = bb.bBoxSW;
  const [r, t] = bb.bBoxNE;
  const f = (v) => +v.toFixed(4);
  boxes.push(
    `  ${name}: { w: ${f(r - l)}, h: ${f(t - b)}, left: ${f(l)}, right: ${f(r)}, top: ${f(
      t,
    )}, bottom: ${f(b)} },`,
  );
}

const anchors = [];
for (const name of ["noteheadBlack", "noteheadHalf", "noteheadWhole"]) {
  const a = meta.glyphsWithAnchors?.[name];
  if (!a?.stemUpSE || !a?.stemDownNW) continue;
  const f = (v) => +v.toFixed(4);
  anchors.push(
    `  ${name}: { upSE: [${f(a.stemUpSE[0])}, ${f(a.stemUpSE[1])}], downNW: [${f(
      a.stemDownNW[0],
    )}, ${f(a.stemDownNW[1])}] },`,
  );
}

const out = `/**
 * bravura.ts — GENERATED by scripts/extract-bravura.mjs. Do not edit by hand.
 *
 * Glyph outlines from the Bravura music font (the SMuFL reference font), so the score is
 * engraved with real notation shapes. Only the glyphs this app draws are vendored; no
 * font file is shipped or loaded at runtime.
 *
 * Bravura is Copyright (c) Steinberg Media Technologies GmbH (http://www.steinberg.net/),
 * with Reserved Font Name "Bravura", licensed under the SIL Open Font License 1.1.
 * Full text: docs/licenses/Bravura-OFL-1.1.txt
 *
 * COORDINATES: font units, y pointing UP, 1000 units per em. SMuFL defines one em as four
 * staff spaces, so one staff space is 250 units. Render with
 *     transform="translate(x y) scale(sp/250, -sp/250)"
 * (see glyphAt) — this converts to pixels and flips y onto SVG's downward axis, with no
 * lossy rewriting of the outlines.
 */

/** Font units per staff space (SMuFL: 1 em = 4 staff spaces; Bravura upem = 1000). */
export const UNITS_PER_SPACE = 250;

/** Font units → pixels for a given staff-space size. */
export const unitScale = (sp: number): number => sp / UNITS_PER_SPACE;

/** SVG transform placing a glyph's origin at (x, y) px, flipping font y-up to screen y-down. */
export function glyphAt(x: number, y: number, sp: number): string {
  const s = unitScale(sp);
  return \`translate(\${x} \${y}) scale(\${s} \${-s})\`;
}

export interface GlyphBox {
  /** Extents in STAFF SPACES relative to the glyph origin, y up. */
  w: number;
  h: number;
  left: number;
  right: number;
  top: number;
  bottom: number;
}

/** Outline path data, font units, y-up. */
export const BRAVURA: Record<string, string> = {
${paths.join("\n")}
};

/** Glyph bounding boxes in staff spaces (bravura_metadata.json), y-up. */
export const BBOX: Record<string, GlyphBox> = {
${boxes.join("\n")}
};

/**
 * Where a stem meets a notehead, in staff spaces from the glyph origin (y up).
 * upSE = bottom-right (up stem); downNW = top-left (down stem).
 */
export const STEM_ANCHOR: Record<string, { upSE: [number, number]; downNW: [number, number] }> = {
${anchors.join("\n")}
};
`;

writeFileSync(OUT, out, "utf8");
console.log(`wrote ${OUT} — ${paths.length} paths, ${boxes.length} boxes, ${anchors.length} anchors`);
